const recUserData = [
    {
        username: "ANUJ KUMAR",
        avatar: "https://avatars.githubusercontent.com/u/1?v=4",
        selfProject: 3,
        totalCommits: 20,
        totalInterviews: 2,
        workingHours: 100,
        education: "MCA",
        performance: 0,
        skills: "React.js, JavaScript, Node.js, MongoDB,Java",
    },
    {
        username: "ANUJ KUMAR",
        avatar: "https://avatars.githubusercontent.com/u/1?v=4",
        selfProject: 3,
        totalCommits: 20,
        totalInterviews: 2,
        workingHours: 100,
        education: "MCA",
        performance: 0,
        skills: "React.js, JavaScript, Node.js, MongoDB,Java",
    },
    {
        username: "RAVI SHARMA",
        avatar: "https://avatars.githubusercontent.com/u/2?v=4",
        selfProject: 5,
        totalCommits: 15,
        totalInterviews: 3,
        workingHours: 220,
        education: "B.tech",
        performance: 0,
        skills: "React.js, JavaScript, Node.js, MongoDB,Java ,React.js, JavaScript, Node.js, MongoDB",
    },
    {
        username: "RAVI SHARMA",
        avatar: "https://avatars.githubusercontent.com/u/2?v=4",
        selfProject: 5,
        totalCommits: 15,
        totalInterviews: 3,
        workingHours: 220,
        education: "B.tech",
        performance: 0,
        skills: "React.js, JavaScript, Node.js, MongoDB,Java ,React.js, JavaScript, Node.js, MongoDB",
    },
    {
        username: "NARAYAN SHARMA",
        avatar: "https://avatars.githubusercontent.com/u/3?v=4",
        selfProject: 2,
        totalCommits: 25,
        totalInterviews: 1,
        workingHours: 90,
        education: "MCA",
        performance: 0,
        skills: "React.js, JavaScript, Node.js",
    },
    {
        username: "NARAYAN SHARMA",
        avatar: "https://avatars.githubusercontent.com/u/3?v=4",
        selfProject: 2,
        totalCommits: 25,
        totalInterviews: 1,
        workingHours: 90,
        education: "MCA",
        performance: 0,
        skills: "React.js, JavaScript, Node.js",
    },
    {
        username: "MOHIT KUMAR",
        avatar: "https://avatars.githubusercontent.com/u/4?v=4",
        selfProject: 1,
        totalCommits: 30,
        totalInterviews: 0,
        workingHours: 10,
        education: "BA",
        performance: 0,
        skills: "React.js, JavaScript",
    },
    {
        username: "MOHIT KUMAR",
        avatar: "https://avatars.githubusercontent.com/u/4?v=4",
        selfProject: 1,
        totalCommits: 30,
        totalInterviews: 0,
        workingHours: 10,
        education: "BA",
        performance: 0,
        skills: "React.js, JavaScript",
    },
];
export default recUserData